sonar.projectKey=edusaas-backend
sonar.projectName=edusaas-backend
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/*.spec.ts
sonar.exclusions=dist/**,node_modules/**,coverage/**,src/**/*.spec.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
