import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1774923996052 implements MigrationInterface {
    name = 'InitialSchema1774923996052'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE EXTENSION IF NOT EXISTS "uuid-ossp"`);
        await queryRunner.query(`CREATE TYPE "public"."school_configs_gradingscale_enum" AS ENUM('numeric_20', 'numeric_10', 'literal')`);
        await queryRunner.query(`CREATE TABLE "school_configs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "schoolId" uuid NOT NULL, "logoUrl" character varying(255), "primaryColor" character varying(30) NOT NULL DEFAULT '28 126 214', "secondaryColor" character varying(30) NOT NULL DEFAULT '14 165 233', "principalName" character varying(150), "gradingScale" "public"."school_configs_gradingscale_enum" NOT NULL DEFAULT 'numeric_20', "schoolRules" text NOT NULL DEFAULT '', CONSTRAINT "UQ_7d865ff81f62bdb7bbe752b8f3a" UNIQUE ("schoolId"), CONSTRAINT "REL_7d865ff81f62bdb7bbe752b8f3" UNIQUE ("schoolId"), CONSTRAINT "PK_c760cd9bc4905499c2cd5f24985" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "schools" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying(150) NOT NULL, "slug" character varying(150) NOT NULL, "contactEmail" character varying(150), "isActive" boolean NOT NULL DEFAULT true, CONSTRAINT "UQ_150b12170135ff067a24ea270dc" UNIQUE ("slug"), CONSTRAINT "PK_95b932e47ac129dd8e23a0db548" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('platform_user', 'super_admin', 'school_admin', 'teacher', 'student', 'parent')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "schoolId" uuid, "firstName" character varying(100) NOT NULL, "lastName" character varying(100) NOT NULL, "phoneNumber" character varying(30), "email" character varying(180) NOT NULL, "avatarUrl" character varying(255), "passwordHash" character varying(255) NOT NULL, "role" "public"."users_role_enum" NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "refreshTokenHash" character varying(255), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "academic_cycles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "schoolId" uuid NOT NULL, "name" character varying(120) NOT NULL, "year" integer NOT NULL DEFAULT '2026', "term" character varying(40), "startDate" date, "endDate" date, "isClosed" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_df69b07fb3253f34d6a80897820" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "courses" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "schoolId" uuid NOT NULL, "name" character varying(140) NOT NULL, "code" character varying(40), "area" character varying(120), "isActive" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_3f70a487cc718ad8eda4e6d58c9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "grades" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "schoolId" uuid NOT NULL, "name" character varying(100) NOT NULL, "level" character varying(30) NOT NULL DEFAULT 'primary', "order" integer NOT NULL, "description" character varying(180), "isActive" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_4740fb6f5df2505a48649f1687b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sections" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "schoolId" uuid NOT NULL, "cycleId" uuid NOT NULL, "gradeId" uuid NOT NULL, "name" character varying(100) NOT NULL, "capacity" integer, "isActive" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_f9749dd3bffd880a497d007e450" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "classes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "schoolId" uuid NOT NULL, "cycleId" uuid NOT NULL, "gradeId" uuid NOT NULL, "sectionId" uuid NOT NULL, "courseId" uuid, "name" character varying(150) NOT NULL, "subject" character varying(150), "displayName" character varying(180), "teacherId" uuid, "isActive" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_e207aa15404e9b2ce35910f9f7f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "student_class_assignments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "schoolId" uuid NOT NULL, "studentId" uuid NOT NULL, "classId" uuid NOT NULL, CONSTRAINT "UQ_e166175339b5f8089950aac1d35" UNIQUE ("studentId", "classId"), CONSTRAINT "PK_a808cacc431df1b41333ff4f76e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."school_memberships_role_enum" AS ENUM('platform_user', 'super_admin', 'school_admin', 'teacher', 'student', 'parent')`);
        await queryRunner.query(`CREATE TYPE "public"."school_memberships_status_enum" AS ENUM('pending', 'active', 'inactive')`);
        await queryRunner.query(`CREATE TABLE "school_memberships" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "schoolId" uuid NOT NULL, "userId" uuid NOT NULL, "role" "public"."school_memberships_role_enum" NOT NULL, "status" "public"."school_memberships_status_enum" NOT NULL DEFAULT 'active', "invitedByUserId" uuid, "joinedAt" TIMESTAMP, CONSTRAINT "UQ_56d83eb1488bfa23a2b33af068f" UNIQUE ("schoolId", "userId", "role"), CONSTRAINT "PK_07a328e1d9134f7e7516758c240" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2b21f6f70cfcea6fb97b458fb8" ON "school_memberships" ("userId", "status") `);
        await queryRunner.query(`CREATE TYPE "public"."school_invitations_role_enum" AS ENUM('platform_user', 'super_admin', 'school_admin', 'teacher', 'student', 'parent')`);
        await queryRunner.query(`CREATE TYPE "public"."school_invitations_status_enum" AS ENUM('pending', 'accepted', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "school_invitations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "schoolId" uuid NOT NULL, "email" character varying(180) NOT NULL, "role" "public"."school_invitations_role_enum" NOT NULL, "status" "public"."school_invitations_status_enum" NOT NULL DEFAULT 'pending', "invitedByUserId" uuid, "acceptedByUserId" uuid, "acceptedAt" TIMESTAMP, CONSTRAINT "UQ_4963609c2a39be46c444b959751" UNIQUE ("schoolId", "email", "role"), CONSTRAINT "PK_e59e5b08d5110c8d4146dbe86ae" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_92be3cf6193a0a772f77ec222a" ON "school_invitations" ("email", "status") `);
        await queryRunner.query(`CREATE TABLE "parent_student_links" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "schoolId" uuid NOT NULL, "parentId" uuid NOT NULL, "studentId" uuid NOT NULL, CONSTRAINT "UQ_3c20304d564f24c4b999aa3d5f0" UNIQUE ("parentId", "studentId"), CONSTRAINT "PK_09f183319d522d110c93b756868" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."tasks_tasktype_enum" AS ENUM('homework', 'practice', 'exam', 'project', 'participation', 'other')`);
        await queryRunner.query(`CREATE TYPE "public"."tasks_submissionmode_enum" AS ENUM('student_submission', 'teacher_only')`);
        await queryRunner.query(`CREATE TABLE "tasks" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "schoolId" uuid NOT NULL, "classId" uuid NOT NULL, "teacherId" uuid, "title" character varying(180) NOT NULL, "description" text NOT NULL, "taskType" "public"."tasks_tasktype_enum" NOT NULL DEFAULT 'homework', "submissionMode" "public"."tasks_submissionmode_enum" NOT NULL DEFAULT 'student_submission', "affectsGrade" boolean NOT NULL DEFAULT true, "maxScore" numeric(8,2), "attachmentUrl" character varying(1000), "attachmentName" character varying(255), "attachmentMimeType" character varying(160), "attachmentStorageKey" character varying(1000), "attachments" jsonb NOT NULL DEFAULT '[]', "dueDate" date NOT NULL, CONSTRAINT "PK_8d12ff38fcc62aaba2cab748772" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."task_submissions_status_enum" AS ENUM('pending', 'submitted', 'late')`);
        await queryRunner.query(`CREATE TABLE "task_submissions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "schoolId" uuid NOT NULL, "taskId" uuid NOT NULL, "studentId" uuid NOT NULL, "content" text, "status" "public"."task_submissions_status_enum" NOT NULL DEFAULT 'pending', "submittedAt" TIMESTAMP, CONSTRAINT "UQ_e0c1191d5285800ebb86cbabced" UNIQUE ("taskId", "studentId"), CONSTRAINT "PK_8d19d6b5dd776e373113de50018" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "task_grades" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "schoolId" uuid NOT NULL, "taskId" uuid NOT NULL, "studentId" uuid NOT NULL, "rawScore" double precision NOT NULL, "scaledScore" character varying(20) NOT NULL, "feedback" text, "gradedAt" TIMESTAMP, CONSTRAINT "UQ_e8d9272e5767527c48caf7479bd" UNIQUE ("taskId", "studentId"), CONSTRAINT "PK_59c40c20d77bada19c4ace07f00" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "schoolId" uuid NOT NULL, "userId" uuid NOT NULL, "title" character varying(180) NOT NULL, "message" text NOT NULL, "isRead" boolean NOT NULL DEFAULT false, "type" character varying(60), "metadata" jsonb NOT NULL DEFAULT '{}'::jsonb, CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "class_grade_configs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "schoolId" uuid NOT NULL, "classId" uuid NOT NULL, "cycleId" uuid NOT NULL, "examsWeight" double precision NOT NULL DEFAULT '20', "participationsWeight" double precision NOT NULL DEFAULT '30', "tasksWeight" double precision NOT NULL DEFAULT '50', "passingScore" double precision NOT NULL DEFAULT '11', "minimumAttendancePercentage" double precision NOT NULL DEFAULT '70', "isClosed" boolean NOT NULL DEFAULT false, CONSTRAINT "UQ_50de7f39782c3ec786f4828d661" UNIQUE ("schoolId", "classId"), CONSTRAINT "PK_23becef9f0c9dc180b6266e6b5c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "grade_records" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "schoolId" uuid NOT NULL, "classId" uuid NOT NULL, "studentId" uuid NOT NULL, "cycleId" uuid NOT NULL, "evaluationName" character varying(150) NOT NULL, "rawScore" numeric(6,2) NOT NULL, "scaledScore" character varying(50) NOT NULL, "isClosed" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_e2f97b9710cdc9fde89ad17e912" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."enrollments_status_enum" AS ENUM('pending', 'accepted', 'rejected')`);
        await queryRunner.query(`CREATE TABLE "enrollments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "schoolId" uuid NOT NULL, "cycleId" uuid NOT NULL, "sectionId" uuid, "firstName" character varying(100) NOT NULL, "lastName" character varying(100) NOT NULL, "email" character varying(180) NOT NULL, "phoneNumber" character varying(30), "birthDate" date, "notes" text, "status" "public"."enrollments_status_enum" NOT NULL DEFAULT 'pending', "studentUserId" uuid, "expedient" jsonb NOT NULL DEFAULT '{}'::jsonb, CONSTRAINT "PK_7c0f752f9fb68bf6ed7367ab00f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."document_templates_type_enum" AS ENUM('certificate', 'constancy', 'report_card', 'custom')`);
        await queryRunner.query(`CREATE TABLE "document_templates" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "schoolId" uuid NOT NULL, "name" character varying(150) NOT NULL, "type" "public"."document_templates_type_enum" NOT NULL DEFAULT 'custom', "htmlContent" text NOT NULL, "isActive" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_0372838b7b7cd3571aef80466d1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."issued_documents_documenttype_enum" AS ENUM('certificate', 'constancy', 'report_card', 'custom')`);
        await queryRunner.query(`CREATE TABLE "issued_documents" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "schoolId" uuid NOT NULL, "templateId" uuid, "studentId" uuid NOT NULL, "issuedById" uuid, "documentType" "public"."issued_documents_documenttype_enum" NOT NULL DEFAULT 'custom', "title" character varying(180) NOT NULL, "fileUrl" character varying(255) NOT NULL, "payload" jsonb NOT NULL DEFAULT '{}', CONSTRAINT "PK_d60beaa56179f62b50ddc014241" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "incidents" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "schoolId" uuid NOT NULL, "studentId" uuid NOT NULL, "reportedById" uuid, "severity" character varying(20) NOT NULL, "description" text NOT NULL, CONSTRAINT "PK_ccb34c01719889017e2246469f9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "schedules" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "schoolId" uuid NOT NULL, "classId" uuid NOT NULL, "dayOfWeek" character varying(20) NOT NULL, "startTime" character varying(5) NOT NULL, "endTime" character varying(5) NOT NULL, "room" character varying(100), CONSTRAINT "PK_7e33fc2ea755a5765e3564e66dd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "audit_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "userId" uuid, "action" character varying(100) NOT NULL, "entityType" character varying(100) NOT NULL, "entityId" character varying(100), "schoolId" uuid, "metadata" jsonb NOT NULL DEFAULT '{}'::jsonb, CONSTRAINT "PK_1bb179d048bbc581caa3b013439" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_1a42d1824a7c74ee392ed9eb30" ON "audit_logs" ("schoolId", "createdAt") `);
        await queryRunner.query(`CREATE TYPE "public"."attendance_records_status_enum" AS ENUM('present', 'absent', 'late')`);
        await queryRunner.query(`CREATE TABLE "attendance_records" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "schoolId" uuid NOT NULL, "classId" uuid NOT NULL, "studentId" uuid NOT NULL, "attendanceDate" date NOT NULL, "status" "public"."attendance_records_status_enum" NOT NULL, "remarks" text, CONSTRAINT "UQ_6ee1e2847f515ead20e808b78ec" UNIQUE ("classId", "studentId", "attendanceDate"), CONSTRAINT "PK_946920332f5bc9efad3f3023b96" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."announcements_type_enum" AS ENUM('announcement', 'reminder', 'material', 'link')`);
        await queryRunner.query(`CREATE TABLE "announcements" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "schoolId" uuid NOT NULL, "classId" uuid NOT NULL, "teacherId" uuid, "title" character varying(180) NOT NULL, "message" text NOT NULL, "type" "public"."announcements_type_enum" NOT NULL DEFAULT 'announcement', "linkUrl" character varying(500), "attachmentUrl" character varying(1000), "attachmentName" character varying(255), "attachmentMimeType" character varying(160), "attachmentStorageKey" character varying(1000), "attachments" jsonb NOT NULL DEFAULT '[]', CONSTRAINT "PK_b3ad760876ff2e19d58e05dc8b0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "announcement_comments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "schoolId" uuid NOT NULL, "announcementId" uuid NOT NULL, "userId" uuid NOT NULL, "message" text NOT NULL, CONSTRAINT "PK_04abbfe5296e221882f9d7d046e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "grade_course_configs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "schoolId" uuid NOT NULL, "gradeId" uuid NOT NULL, "courseId" uuid NOT NULL, "isRequired" boolean NOT NULL DEFAULT true, "weeklyHours" integer, "order" integer NOT NULL DEFAULT '1', "isActive" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_366391a288f34035febb1a323bf" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "school_configs" ADD CONSTRAINT "FK_7d865ff81f62bdb7bbe752b8f3a" FOREIGN KEY ("schoolId") REFERENCES "schools"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_435e192698a6b7d10849295643d" FOREIGN KEY ("schoolId") REFERENCES "schools"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "academic_cycles" ADD CONSTRAINT "FK_28b54567871fbad9f163d3ca308" FOREIGN KEY ("schoolId") REFERENCES "schools"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "courses" ADD CONSTRAINT "FK_9689700fc21294dc6abbb0e3180" FOREIGN KEY ("schoolId") REFERENCES "schools"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sections" ADD CONSTRAINT "FK_d12e75419cc8db38fe2104b581c" FOREIGN KEY ("cycleId") REFERENCES "academic_cycles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sections" ADD CONSTRAINT "FK_8eb5f422b2a34cc7bf9039e2231" FOREIGN KEY ("gradeId") REFERENCES "grades"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "classes" ADD CONSTRAINT "FK_6c126e8e4ea715042e6226c8025" FOREIGN KEY ("cycleId") REFERENCES "academic_cycles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "classes" ADD CONSTRAINT "FK_2a35ec6dd05f3001ff688bf7cd2" FOREIGN KEY ("gradeId") REFERENCES "grades"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "classes" ADD CONSTRAINT "FK_db018f5603d2552be9becf68690" FOREIGN KEY ("sectionId") REFERENCES "sections"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "classes" ADD CONSTRAINT "FK_91fb6af6df84c442e4a15b17609" FOREIGN KEY ("courseId") REFERENCES "courses"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "classes" ADD CONSTRAINT "FK_4b7ac7a7eb91f3e04229c7c0b6f" FOREIGN KEY ("teacherId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "student_class_assignments" ADD CONSTRAINT "FK_7e3306c7e9ce1b9dfec648b4414" FOREIGN KEY ("studentId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "student_class_assignments" ADD CONSTRAINT "FK_1750bcda35d941aedae85c64b1f" FOREIGN KEY ("classId") REFERENCES "classes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "school_memberships" ADD CONSTRAINT "FK_153d83145e6e4debc5514d784a5" FOREIGN KEY ("schoolId") REFERENCES "schools"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "school_memberships" ADD CONSTRAINT "FK_bd3e90abec9a847507df98466cb" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "parent_student_links" ADD CONSTRAINT "FK_db5f55c072f54180fc54122f443" FOREIGN KEY ("parentId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "parent_student_links" ADD CONSTRAINT "FK_d822a0766d7ccb9e6b1b3e11958" FOREIGN KEY ("studentId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "FK_d1dbb1c22c741fc8e1f4d1bc436" FOREIGN KEY ("classId") REFERENCES "classes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "FK_1b3650080cad6b0597648ebeb45" FOREIGN KEY ("teacherId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task_submissions" ADD CONSTRAINT "FK_8b64cdeb41cbea6ce153dde4881" FOREIGN KEY ("taskId") REFERENCES "tasks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task_submissions" ADD CONSTRAINT "FK_8a83a1db1ec707bd4290b33758c" FOREIGN KEY ("studentId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task_grades" ADD CONSTRAINT "FK_c79493125fa1734a46a11eb035d" FOREIGN KEY ("taskId") REFERENCES "tasks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task_grades" ADD CONSTRAINT "FK_ef9f756d71b18362e6ffa22090c" FOREIGN KEY ("studentId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_692a909ee0fa9383e7859f9b406" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "class_grade_configs" ADD CONSTRAINT "FK_5c4e599dd4b96fb629984de2c8d" FOREIGN KEY ("classId") REFERENCES "classes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "grade_records" ADD CONSTRAINT "FK_c69a8cbbc949f855a64a87a8b59" FOREIGN KEY ("classId") REFERENCES "classes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "grade_records" ADD CONSTRAINT "FK_d7515c85b45fcf7cfcb270c4672" FOREIGN KEY ("studentId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "enrollments" ADD CONSTRAINT "FK_c3070e8e34cbfffaf09724f9aa0" FOREIGN KEY ("cycleId") REFERENCES "academic_cycles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "enrollments" ADD CONSTRAINT "FK_e0edac70a2adb9b921a8437bfa7" FOREIGN KEY ("sectionId") REFERENCES "sections"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "enrollments" ADD CONSTRAINT "FK_74171461b96df81cdcc74e86c7e" FOREIGN KEY ("studentUserId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "issued_documents" ADD CONSTRAINT "FK_b97324a2f0543114e1a9f5dfb2e" FOREIGN KEY ("templateId") REFERENCES "document_templates"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "issued_documents" ADD CONSTRAINT "FK_bc88df698a796afc59dc0572d4f" FOREIGN KEY ("studentId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "issued_documents" ADD CONSTRAINT "FK_3d9a7038e1d2b67715afd522b04" FOREIGN KEY ("issuedById") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "incidents" ADD CONSTRAINT "FK_89ae74d66175bbeaa18d2773aac" FOREIGN KEY ("studentId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "incidents" ADD CONSTRAINT "FK_9f2e530317309ad9b7dccbff578" FOREIGN KEY ("reportedById") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "schedules" ADD CONSTRAINT "FK_0749b1cdc0bbcf2d05405e3c443" FOREIGN KEY ("classId") REFERENCES "classes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance_records" ADD CONSTRAINT "FK_e67d679e0a28fe37b52347863cd" FOREIGN KEY ("classId") REFERENCES "classes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance_records" ADD CONSTRAINT "FK_21f6cf258d12a2432bd2a8f798d" FOREIGN KEY ("studentId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "announcements" ADD CONSTRAINT "FK_c22586dee42cd7d0b57d3ab5893" FOREIGN KEY ("classId") REFERENCES "classes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "announcements" ADD CONSTRAINT "FK_9e8a8ccf38332d27ced5e1fbf79" FOREIGN KEY ("teacherId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "announcement_comments" ADD CONSTRAINT "FK_2da728a8f3e2d5f4108e0ef9124" FOREIGN KEY ("announcementId") REFERENCES "announcements"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "announcement_comments" ADD CONSTRAINT "FK_9c76376270e650844ce53ca672c" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "grade_course_configs" ADD CONSTRAINT "FK_fcb48244441edeb029a429414ed" FOREIGN KEY ("gradeId") REFERENCES "grades"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "grade_course_configs" ADD CONSTRAINT "FK_81842238fe34596da7bc3d2282a" FOREIGN KEY ("courseId") REFERENCES "courses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "grade_course_configs" DROP CONSTRAINT "FK_81842238fe34596da7bc3d2282a"`);
        await queryRunner.query(`ALTER TABLE "grade_course_configs" DROP CONSTRAINT "FK_fcb48244441edeb029a429414ed"`);
        await queryRunner.query(`ALTER TABLE "announcement_comments" DROP CONSTRAINT "FK_9c76376270e650844ce53ca672c"`);
        await queryRunner.query(`ALTER TABLE "announcement_comments" DROP CONSTRAINT "FK_2da728a8f3e2d5f4108e0ef9124"`);
        await queryRunner.query(`ALTER TABLE "announcements" DROP CONSTRAINT "FK_9e8a8ccf38332d27ced5e1fbf79"`);
        await queryRunner.query(`ALTER TABLE "announcements" DROP CONSTRAINT "FK_c22586dee42cd7d0b57d3ab5893"`);
        await queryRunner.query(`ALTER TABLE "attendance_records" DROP CONSTRAINT "FK_21f6cf258d12a2432bd2a8f798d"`);
        await queryRunner.query(`ALTER TABLE "attendance_records" DROP CONSTRAINT "FK_e67d679e0a28fe37b52347863cd"`);
        await queryRunner.query(`ALTER TABLE "schedules" DROP CONSTRAINT "FK_0749b1cdc0bbcf2d05405e3c443"`);
        await queryRunner.query(`ALTER TABLE "incidents" DROP CONSTRAINT "FK_9f2e530317309ad9b7dccbff578"`);
        await queryRunner.query(`ALTER TABLE "incidents" DROP CONSTRAINT "FK_89ae74d66175bbeaa18d2773aac"`);
        await queryRunner.query(`ALTER TABLE "issued_documents" DROP CONSTRAINT "FK_3d9a7038e1d2b67715afd522b04"`);
        await queryRunner.query(`ALTER TABLE "issued_documents" DROP CONSTRAINT "FK_bc88df698a796afc59dc0572d4f"`);
        await queryRunner.query(`ALTER TABLE "issued_documents" DROP CONSTRAINT "FK_b97324a2f0543114e1a9f5dfb2e"`);
        await queryRunner.query(`ALTER TABLE "enrollments" DROP CONSTRAINT "FK_74171461b96df81cdcc74e86c7e"`);
        await queryRunner.query(`ALTER TABLE "enrollments" DROP CONSTRAINT "FK_e0edac70a2adb9b921a8437bfa7"`);
        await queryRunner.query(`ALTER TABLE "enrollments" DROP CONSTRAINT "FK_c3070e8e34cbfffaf09724f9aa0"`);
        await queryRunner.query(`ALTER TABLE "grade_records" DROP CONSTRAINT "FK_d7515c85b45fcf7cfcb270c4672"`);
        await queryRunner.query(`ALTER TABLE "grade_records" DROP CONSTRAINT "FK_c69a8cbbc949f855a64a87a8b59"`);
        await queryRunner.query(`ALTER TABLE "class_grade_configs" DROP CONSTRAINT "FK_5c4e599dd4b96fb629984de2c8d"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_692a909ee0fa9383e7859f9b406"`);
        await queryRunner.query(`ALTER TABLE "task_grades" DROP CONSTRAINT "FK_ef9f756d71b18362e6ffa22090c"`);
        await queryRunner.query(`ALTER TABLE "task_grades" DROP CONSTRAINT "FK_c79493125fa1734a46a11eb035d"`);
        await queryRunner.query(`ALTER TABLE "task_submissions" DROP CONSTRAINT "FK_8a83a1db1ec707bd4290b33758c"`);
        await queryRunner.query(`ALTER TABLE "task_submissions" DROP CONSTRAINT "FK_8b64cdeb41cbea6ce153dde4881"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "FK_1b3650080cad6b0597648ebeb45"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "FK_d1dbb1c22c741fc8e1f4d1bc436"`);
        await queryRunner.query(`ALTER TABLE "parent_student_links" DROP CONSTRAINT "FK_d822a0766d7ccb9e6b1b3e11958"`);
        await queryRunner.query(`ALTER TABLE "parent_student_links" DROP CONSTRAINT "FK_db5f55c072f54180fc54122f443"`);
        await queryRunner.query(`ALTER TABLE "school_memberships" DROP CONSTRAINT "FK_bd3e90abec9a847507df98466cb"`);
        await queryRunner.query(`ALTER TABLE "school_memberships" DROP CONSTRAINT "FK_153d83145e6e4debc5514d784a5"`);
        await queryRunner.query(`ALTER TABLE "student_class_assignments" DROP CONSTRAINT "FK_1750bcda35d941aedae85c64b1f"`);
        await queryRunner.query(`ALTER TABLE "student_class_assignments" DROP CONSTRAINT "FK_7e3306c7e9ce1b9dfec648b4414"`);
        await queryRunner.query(`ALTER TABLE "classes" DROP CONSTRAINT "FK_4b7ac7a7eb91f3e04229c7c0b6f"`);
        await queryRunner.query(`ALTER TABLE "classes" DROP CONSTRAINT "FK_91fb6af6df84c442e4a15b17609"`);
        await queryRunner.query(`ALTER TABLE "classes" DROP CONSTRAINT "FK_db018f5603d2552be9becf68690"`);
        await queryRunner.query(`ALTER TABLE "classes" DROP CONSTRAINT "FK_2a35ec6dd05f3001ff688bf7cd2"`);
        await queryRunner.query(`ALTER TABLE "classes" DROP CONSTRAINT "FK_6c126e8e4ea715042e6226c8025"`);
        await queryRunner.query(`ALTER TABLE "sections" DROP CONSTRAINT "FK_8eb5f422b2a34cc7bf9039e2231"`);
        await queryRunner.query(`ALTER TABLE "sections" DROP CONSTRAINT "FK_d12e75419cc8db38fe2104b581c"`);
        await queryRunner.query(`ALTER TABLE "courses" DROP CONSTRAINT "FK_9689700fc21294dc6abbb0e3180"`);
        await queryRunner.query(`ALTER TABLE "academic_cycles" DROP CONSTRAINT "FK_28b54567871fbad9f163d3ca308"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_435e192698a6b7d10849295643d"`);
        await queryRunner.query(`ALTER TABLE "school_configs" DROP CONSTRAINT "FK_7d865ff81f62bdb7bbe752b8f3a"`);
        await queryRunner.query(`DROP TABLE "grade_course_configs"`);
        await queryRunner.query(`DROP TABLE "announcement_comments"`);
        await queryRunner.query(`DROP TABLE "announcements"`);
        await queryRunner.query(`DROP TYPE "public"."announcements_type_enum"`);
        await queryRunner.query(`DROP TABLE "attendance_records"`);
        await queryRunner.query(`DROP TYPE "public"."attendance_records_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1a42d1824a7c74ee392ed9eb30"`);
        await queryRunner.query(`DROP TABLE "audit_logs"`);
        await queryRunner.query(`DROP TABLE "schedules"`);
        await queryRunner.query(`DROP TABLE "incidents"`);
        await queryRunner.query(`DROP TABLE "issued_documents"`);
        await queryRunner.query(`DROP TYPE "public"."issued_documents_documenttype_enum"`);
        await queryRunner.query(`DROP TABLE "document_templates"`);
        await queryRunner.query(`DROP TYPE "public"."document_templates_type_enum"`);
        await queryRunner.query(`DROP TABLE "enrollments"`);
        await queryRunner.query(`DROP TYPE "public"."enrollments_status_enum"`);
        await queryRunner.query(`DROP TABLE "grade_records"`);
        await queryRunner.query(`DROP TABLE "class_grade_configs"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP TABLE "task_grades"`);
        await queryRunner.query(`DROP TABLE "task_submissions"`);
        await queryRunner.query(`DROP TYPE "public"."task_submissions_status_enum"`);
        await queryRunner.query(`DROP TABLE "tasks"`);
        await queryRunner.query(`DROP TYPE "public"."tasks_submissionmode_enum"`);
        await queryRunner.query(`DROP TYPE "public"."tasks_tasktype_enum"`);
        await queryRunner.query(`DROP TABLE "parent_student_links"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_92be3cf6193a0a772f77ec222a"`);
        await queryRunner.query(`DROP TABLE "school_invitations"`);
        await queryRunner.query(`DROP TYPE "public"."school_invitations_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."school_invitations_role_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2b21f6f70cfcea6fb97b458fb8"`);
        await queryRunner.query(`DROP TABLE "school_memberships"`);
        await queryRunner.query(`DROP TYPE "public"."school_memberships_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."school_memberships_role_enum"`);
        await queryRunner.query(`DROP TABLE "student_class_assignments"`);
        await queryRunner.query(`DROP TABLE "classes"`);
        await queryRunner.query(`DROP TABLE "sections"`);
        await queryRunner.query(`DROP TABLE "grades"`);
        await queryRunner.query(`DROP TABLE "courses"`);
        await queryRunner.query(`DROP TABLE "academic_cycles"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
        await queryRunner.query(`DROP TABLE "schools"`);
        await queryRunner.query(`DROP TABLE "school_configs"`);
        await queryRunner.query(`DROP TYPE "public"."school_configs_gradingscale_enum"`);
    }

}
